# Generated by Django 5.2.8 on 2025-11-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='CarBooking',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seat_capacity',
        ),
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='SUV', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='Petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Manual', max_length=50),
        ),
    ]
