# Generated by Django 5.2.8 on 2025-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_booking_carbooking_remove_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='customer_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='customer_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
